Redesign website
kyma-project/website pull request #620
Opened 2020-09-01 14:08 UTC by tgorgol

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2020-09-01 14:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/website?pullRequest=620) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/website?pullRequest=620) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/website?pullRequest=620) it.</sub>

2020-09-09 10:35 UTC, kazydek commented on content/i18n/en/siteMetadata.json
> +  "description": "Kyma is a cloud-native application runtime that gives you the power of Kubernetes but without the hassle of worrying about security, configuration, and integration of tools.",
This description should reflect our manifesto - as you can see in [PR 495](https://github.com/kyma-project/community/pull/495/files), it has not been decided yet what these abstracts would look like. For now, I would stick to what you have above (and what was used in the design).

2020-09-09 10:50 UTC, aerfio requested changes
Looks nice! Make sure you've minified svgs using svgo or some other tool (if they are mangled after this operation then just leave them as they are)

2020-09-09 10:50 UTC, aerfio commented on src/common/i18n/flattenMessages.ts
> +    if (typeof value === "string" || Array.isArray(value)) {
I'd rather have proper types here, so while you're here could you somehow create proper types for this function? We need to get rid of that damn `any` in order to facilitate future work here

2020-09-09 10:50 UTC, aerfio commented on src/views/landingPage/Features/FeatureCard/index.tsx
> +import Support from "@views/landingPage/assets/landing-page/features/support.svg";
change those imports to something like `extensibilitySVG`, as the proper practice is that in React we use capitalised imports for components

2020-09-09 10:50 UTC, aerfio commented on src/views/landingPage/Manifesto/index.tsx
> +const scrollToFeatures = (e: any) => {
React.MouseEvent<HTMLAnchorElement, MouseEvent> instead of any

2020-09-09 14:11 UTC, magicmatatjahu approved these changes

2020-09-09 14:16 UTC, valentinvieriu commented on src/views/landingPage/Features/Header/styled.ts
> +export const SpellingOfText = styled.pre`
Can we use paragraph in here, just for SEO consistency?

2020-09-09 14:18 UTC, valentinvieriu commented
Can we use paragraph and h2 without span? It's a small change, but for SEO consistency
![image](https://user-images.githubusercontent.com/478866/92610516-0fba6700-f2b8-11ea-8602-1ae0d38ba72a.png)

2020-09-09 14:20 UTC, valentinvieriu commented on content/i18n/en/siteMetadata.json
> +  "description": "Kyma is a cloud-native application runtime that gives you the power of Kubernetes but without the hassle of worrying about security, configuration, and integration of tools.",
Yes. The final text will be in a separate issue, unfortunately.

2020-09-09 14:25 UTC, valentinvieriu commented on src/views/landingPage/Features/FeatureCard/index.tsx
> +      <img src={getImageForFeature(feature)} />
Please add alt attribute. Google Lighthouse complains about this
![image](https://user-images.githubusercontent.com/478866/92611377-02ea4300-f2b9-11ea-9f7a-10419b1225fc.png)

2020-09-09 14:27 UTC, valentinvieriu commented on src/views/landingPage/Manifesto/index.tsx
> +              <FormattedMessage id={gt("githubButton")} />
It seems lighthouse complains here too
[Link-name](https://web.dev/link-name/?utm_source=lighthouse&utm_medium=devtools)
I believe we need to add some text like : "Scroll to next section" that is hidden

2020-09-09 14:35 UTC, valentinvieriu commented on src/views/landingPage/Features/FeatureCard/index.tsx
> +      <img src={getImageForFeature(feature)} />
can we also force a fixed width here. It seem sthe SVGs are not the same size
237 sounds like a round number :)
![image](https://user-images.githubusercontent.com/478866/92612356-1518b100-f2ba-11ea-8009-a108b1c5ed07.png)

2020-09-10 09:28 UTC, magicmatatjahu submitted a review, later dismissed

2020-09-10 10:01 UTC, aerfio approved these changes

2020-09-10 10:36 UTC, aerfio approved these changes

2020-09-10 10:36 UTC, magicmatatjahu approved these changes

2020-09-10 10:37 UTC, kazydek approved these changes
As agreed, approving only for development purposes - texts are not final.

2020-09-10 10:59 UTC, merged