Fix bug
kyma-project/website pull request #664
Opened 2021-01-13 13:54 UTC by pPrecel

**Description**

Changes proposed in this pull request:

- Upgrade link mechanism

**Related issue(s)**

https://github.com/kyma-project/website/issues/591

2021-01-13 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/website?pullRequest=664) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/website?pullRequest=664) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/website?pullRequest=664) it.</sub>

2021-01-13 13:57 UTC, kazydek commented on content/community/content/docs/01-content-strategy.md
> +* [info@kyma-project.io](mailto:info@kyma-project.io)
I don't think it relates to the content strategy 🤔

2021-01-13 13:59 UTC, aerfio commented on content/community/content/docs/01-content-strategy.md
> +* [info@kyma-project.io](mailto:info@kyma-project.io)
This is only content visible during development @kazydek

2021-01-13 14:00 UTC, aerfio requested changes

2021-01-13 14:00 UTC, aerfio commented on src/components/generic-documentation/render-engines/markdown/custom-renderers/Link.tsx
> +  if (href.includes("mailto")) {
please be more specific: `mailto:`

2021-01-13 22:37 UTC, aerfio approved these changes

2021-01-14 08:39 UTC, kazydek approved these changes

2021-01-14 09:46 UTC, merged