Update landing page
kyma-project/website pull request #726
Opened 2021-05-25 14:12 UTC by kwiatekus

**Description**

Changes proposed in this pull request:

- Updated Key features
- Updated In the nutshell
- Updated Manifesto

**Related issue(s)**
https://github.com/kyma-project/website/issues/679

2021-05-26 08:17 UTC, tgorgol commented on content/i18n/en/landing-page.json
> +          "Kyma allows you to trigger workloads ( functions or microservices ) via in-cluster events or extrenal business events"
```suggestion
          "Kyma allows you to trigger workloads (functions or microservices) via in-cluster events or external business events"
```
the space after parentheses causes some weird line breaks:
![image](https://user-images.githubusercontent.com/45565988/119625401-6fd34800-be0a-11eb-811c-7baa5694903f.png)

2021-05-26 08:17 UTC, tgorgol commented on content/i18n/en/landing-page.json
> +          "Kyma empowers developers to easy deploy workloads in form of functions. With Kyma you can focus on coding.",
```suggestion
          "Kyma empowers developers to easily deploy workloads in form of functions. With Kyma you can focus on coding.",
```

2021-05-26 10:17 UTC, tgorgol submitted a review, later dismissed
LGTM 👍

2021-05-26 10:42 UTC, NHingerl requested changes

2021-05-26 10:42 UTC, NHingerl commented on content/i18n/en/landing-page.json
> +    "paragraph": "{brand} {spelling} is a cloud-native application runtime that combines the power of Kubernetes with a set of best-in-class tools and open-source components, that empower you to deve
```suggestion
    "paragraph": "{brand} {spelling} is a cloud-native application runtime that combines the power of Kubernetes with a set of best-in-class tools and open-source components that empower you to develop, run and operate secure and scalable cloud-native applications.",
```

2021-05-26 10:42 UTC, NHingerl commented on content/i18n/en/landing-page.json
> +          "Kyma empowers developers to easily deploy workloads in form of functions. With Kyma you can focus on coding.",
```suggestion
          "Kyma empowers developers to easily deploy workloads in form of Functions. With Kyma, you can focus on coding.",
```

2021-05-26 10:42 UTC, NHingerl commented on content/i18n/en/landing-page.json
> +          "Simply write your function code, add a configuration manifest and push it to Kyma using supporting CLI or directly to git."
```suggestion
          "Simply write your Function code, add a configuration manifest, and push it to Kyma using supporting CLI or directly to git."
```
For "supporting CLI", I think we need an article (_a_ or _the_), or if we refer to Kyma CLI specifically, write something like "using _our_ supporting CLI", or simply "using Kyma CLI".

2021-05-26 10:42 UTC, NHingerl commented on content/i18n/en/landing-page.json
> +          "Kyma allows you to trigger workloads (functions or microservices) via in-cluster events or external business events"
```suggestion
          "With Kyma, you can trigger workloads (Functions or microservices) using in-cluster events or external business events."
```

(according [style guide](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/allow-allows) and [terminology](https://kyma-project.io/community/guidelines/content/#style-and-terminology-style-and-terminology-terminology)).

2021-05-26 10:42 UTC, NHingerl commented on content/i18n/en/landing-page.json
> +          "Kyma comes with pre-configured open-source observability tools. You can easily monitor the performance of your microservices and functions, scan logs for errors and trace request flow thro
```suggestion
          "Kyma comes with pre-configured open-source observability tools. You can easily monitor the performance of your microservices and Functions, scan logs for errors, and trace the request flow through the entire system."
```

2021-05-26 10:42 UTC, NHingerl commented on content/i18n/en/landing-page.json
> +    "paragraph": "With Kyma your workloads are in the center. Kyma helps you to expose their APIs, trigger them with events, enable them for external service consumption and will assure observability
```suggestion
    "paragraph": "With Kyma, your workloads are in the center. Kyma helps you to expose their APIs, trigger them with events, enable them for external service consumption and will assure observability.",
```

The sentence structure might confuse readers. It's basically "Kyma helps you to a, b, c, and [Kyma] will d." Would the last bit still be correct if we write simply "...enable ... consumption, _and assure observability_." ?

2021-05-26 11:48 UTC, kwiatekus commented on content/i18n/en/landing-page.json
> +    "paragraph": "With Kyma your workloads are in the center. Kyma helps you to expose their APIs, trigger them with events, enable them for external service consumption and will assure observability
yes. absolutely. I will push the changes

2021-05-26 11:49 UTC, kwiatekus commented on content/i18n/en/landing-page.json
> +          "Simply write your function code, add a configuration manifest and push it to Kyma using supporting CLI or directly to git."
Added `our` to make it sound better. thx

2021-05-26 15:02 UTC, tgorgol approved these changes

2021-05-27 08:11 UTC, alexandra-simeonova commented on content/i18n/en/landing-page.json
> +    "headline": "In the nutshell",
```suggestion
    "headline": "In a nutshell",
```

"In a nutshell" is the correct expression 🙂  https://dictionary.cambridge.org/dictionary/english/in-a-nutshell

2021-05-27 10:26 UTC, NHingerl approved these changes

2021-05-27 10:39 UTC, tgorgol approved these changes

2021-05-27 10:40 UTC, merged