Fix content fetcher bug
kyma-project/website pull request #833
Opened 2022-03-07 06:47 UTC by Lyczeq

**Description**
Fix content fetcher bug
Changes proposed in this pull request:

- Update Readme file to facilitate development
- Change version comparison
- Remove.needless files

**Related issue(s)**
Fixes #830

2022-03-07 06:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/website?pullRequest=833) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/website?pullRequest=833) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/website?pullRequest=833) it.</sub>

2022-03-08 07:21 UTC, qbalukom requested changes

2022-03-08 07:21 UTC, qbalukom commented on tools/content-loader/src/prepare-docs/release-fetcher.ts
> +        return Number.parseFloat(secondTag) - Number.parseFloat(firstTag);
I don't think this will sort correctly. as version `1.9.0` will be treated as `1.9`, but version `1.10.0` will be treated as `1.1`.
Also it won't distinguish between `1.10.0` and `1.10.1` (as everything after and including the second period will be ignored), not to mention `1.10.0-rc1` vs. `1.10.0-rc2`

2022-03-08 07:21 UTC, qbalukom commented on tools/content-loader/src/prepare-docs/release-fetcher.ts
> +        return Number.parseFloat(secondTag) - Number.parseFloat(firstTag);
there are tools for proper handling of semantic versioning, such as https://github.com/npm/node-semver

2022-03-08 13:47 UTC, grego952 commented on README.md
> +Then go to the root directory of the repostory and run the following command:
```suggestion
Then go to the root directory of the repository and run the following command:
```

2022-03-08 13:47 UTC, grego952 commented on README.md
> +To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change  `APP_DOCS_OUTPUT` to:
```suggestion
To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change `APP_DOCS_OUTPUT` to:
```

2022-03-08 13:50 UTC, grego952 commented on README.md
> +To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change  `APP_DOCS_OUTPUT` to:
```suggestion
To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change `APP_DOCS_OUTPUT` to:
```

2022-03-08 13:50 UTC, grego952 commented on README.md
> +Then go to the root directory of the repostory and run the following command:
```suggestion
Then go to the root directory of the repository and run the following command:
```

2022-03-09 06:49 UTC, grego952 submitted a review, later dismissed

2022-03-09 09:12 UTC, qbalukom requested changes

2022-03-09 09:12 UTC, qbalukom commented on tools/content-loader/src/prepare-docs/release-fetcher.ts
> +    const sortedResult = new Map(
`return new Map(`?
no need to assign to a new variable

2022-03-09 09:12 UTC, qbalukom commented on tools/content-loader/src/prepare-docs/release-fetcher.ts
>        result.set(key, sorted[0]);
i won't lie, i would love to see it done as `groupedReleases.reduce` instead of modifying a variable external to the loop... but it's not part of your changes and not a blocker :)
just if you feel like experimenting :)

2022-03-09 09:55 UTC, qbalukom approved these changes

2022-03-09 09:58 UTC, grego952 approved these changes

2022-03-09 10:00 UTC, merged