Update CODEOWNERS
kyma-project/website pull request #883
Opened 2022-09-19 19:15 UTC by IwonaLanger

**Description**

Changes proposed in this pull request:

An update of the list of code owners.

2022-09-20 06:51 UTC, mrCherry97 requested changes
![image](https://user-images.githubusercontent.com/46759954/191187332-1cfb323f-ef5e-47ea-9cfb-816d4406883f.png)

2022-09-21 15:49 UTC, majakurcius commented
/retest

2022-09-21 15:59 UTC, majakurcius commented
> ![image](https://user-images.githubusercontent.com/46759954/191187332-1cfb323f-ef5e-47ea-9cfb-816d4406883f.png)

For some reason we missed Iwona not having access to the Website repo. It's fixed now. Please approve :)

2022-09-21 16:00 UTC, majakurcius approved these changes

2022-09-22 06:43 UTC, mrCherry97 commented
/retest

2022-09-22 06:44 UTC, mrCherry97 approved these changes

2022-09-22 07:53 UTC, dariadomagala commented
/test all

2022-09-22 07:57 UTC, mrCherry97 commented
/ok-to-test

2022-09-22 08:07 UTC, mrCherry97 commented
done in https://github.com/kyma-project/website/pull/885

2022-09-22 08:07 UTC, closed without merging