Release Notes for Kyma 2.8
kyma-project/website pull request #897
Opened 2022-10-14 12:59 UTC by majakurcius

**Description**

Changes proposed in this pull request:

- Create Release Notes for Kyma 2.8

**Related issue(s)**
https://github.com/kyma-project/website/pull/896

2022-10-17 12:49 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +As preparation for the bigger changes planned in the tracing area (see https://github.com/kyma-project/community/tree/main/concepts/observability-strategy/configurable-tracing) we updated the Jaeger
>we updated the Jaeger stack to the latest version 1.37

@a-thaler I'm afraid it's not the latest version anymore :( They already have [1.38.1 out](https://github.com/jaegertracing/jaeger/releases/tag/v1.38.1).

> At the same time the serverless engine switched to OTLP as well and is ready for the awesome future.
@a-thaler @kwiatekus Do we mean our Serverless here, or is there simply a "serverless engine" somewhere in the Observability area that we're talking about here? I'm not familiar with the domain enough to figure this out on my own.

2022-10-17 13:23 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The Kyma Observability feature got a shift into the direction of integration and openness, to enable enterprise-grade qualities based on external services, see https://kyma-project.io/blog/2022/9/21/
> (...) a tutorial got introduced on how to integrate Kiali on your own (see this links) (...) 

@a-thaler Do you have these links by any chance? They have not been provided so far. 
I suppose one might be this https://github.com/kyma-project/examples/blob/main/kiali/README.md (can you confirm?), but it says `links` (plural), so I don't know what else it could be.

2022-10-17 13:31 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The Kyma Observability feature got a shift into the direction of integration and openness, to enable enterprise-grade qualities based on external services, see https://kyma-project.io/blog/2022/9/21/
@a-thaler 
Also, [our guidelines](https://github.com/kyma-project/community/blob/main/docs/guidelines/content-guidelines/02-style-and-terminology.md#terminology) say not to promise things and to write only about stuff that's already implemented. 
Should we really mention a specific version in which we're going to remove Kiali? 
I'd strongly advise against it, and say `in a future release` at the most. 
WDYT?

2022-10-17 14:03 UTC, NHingerl commented
not sure if that helps solving potential confusion, but the current Obsv draft in OneNote looks like this: 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/76950046/196197778-43b47cba-7a2f-44c6-b868-6bfb969ad22b.png">

2022-10-17 14:17 UTC, a-thaler commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +As preparation for the bigger changes planned in the tracing area (see https://github.com/kyma-project/community/tree/main/concepts/observability-strategy/configurable-tracing) we updated the Jaeger
It is our Serverless. and yes, it is not the latest jaeger anymore, feel free to remove "latest"

2022-10-17 14:19 UTC, a-thaler commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The Kyma Observability feature got a shift into the direction of integration and openness, to enable enterprise-grade qualities based on external services, see https://kyma-project.io/blog/2022/9/21/
I wrote a blog post which we should link: https://kyma-project.io/blog/2022/10/10/Kiali-deprecation/
and yes, the instructions are located at https://github.com/kyma-project/examples/blob/main/kiali/README.md
That are all links we have :)

2022-10-17 14:26 UTC, a-thaler commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The Kyma Observability feature got a shift into the direction of integration and openness, to enable enterprise-grade qualities based on external services, see https://kyma-project.io/blog/2022/9/21/
People need an idea on how much time they still have.. if that promise is not fullfilling no one will be upset but potentially more happy. SO I prefer to keep it, I noted it down in our backlog to keep it

2022-10-17 14:34 UTC, majakurcius commented
Note: The link is expected to not be working for now. It will be once we cut off the release branch.

2022-10-17 14:51 UTC, a-thaler commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +- [Observability](#observability) - update to Jaeger 1.37, `node-exporter` 1.4.0, and Fluent Bit 1.9.9; OTLP support enabled, Secret rotation support for LogPipelines improved, Kiali deprecation
```suggestion
- [Observability](#observability) - Several component updates; Improved secret rotation support for LogPipelines; Kiali deprecation
```

2022-10-17 14:53 UTC, a-thaler commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +In this release, we also updated Prometheus `node-exporter` to version 1.4.0.
```suggestion
In this release, we also updated the Prometheus `node-exporter` to version 1.4.0 and to `kube-state-metrics` to version 2.6.0


```

2022-10-17 14:55 UTC, a-thaler commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +See the [`node-exporter` release notes](https://github.com/prometheus/node_exporter/releases) for more details.
```suggestion
See the [`node-exporter` release notes](https://github.com/prometheus/node_exporter/releases/tag/v1.4.0) and [`kube-state-metrics` release notes](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.6.0) for more details. 
```

2022-10-17 14:56 UTC, a-thaler commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +> **NOTE:** Mind that with [Kyma 2.6](https://kyma-project.io/blog/2022/8/25/release-notes-26/), the Fluent-Bit part of the Logging component was replaced by the new Telemetry component. Fluent Bit w
```suggestion
> **NOTE:** Mind that with [Kyma 2.6](https://kyma-project.io/blog/2022/8/25/release-notes-26/), the Fluent-Bit part of the Logging component was replaced by the new Telemetry component. The Fluent Bit of the logging component will be removed with the next Kyma release. If you have not adopted the change yet, do so now. 
```

2022-10-17 16:14 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +> **NOTE:** Mind that with [Kyma 2.6](https://kyma-project.io/blog/2022/8/25/release-notes-26/), the Fluent-Bit part of the Logging component was replaced by the new Telemetry component. Fluent Bit w
In order to avoid duplication, I propose: 
```
This Fluent Bit part will be removed with the next Kyma release. If you have not adopted the change yet, do so now. ```

2022-10-18 09:37 UTC, IwonaLanger commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +From this release, Application Gateway in Kyma supports redirects for the HTTP requests in which the URL host remains unchanged.
```suggestion
From this release on, Application Gateway in Kyma supports redirects for the HTTP requests in which the URL host remains unchanged.
```

2022-10-18 09:37 UTC, IwonaLanger commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +This Kyma version introduces the Istio CNI plugin. The plugin replaces the Istio `istio-init` container, and it provides the same networking functionality, but it doesn't require Istio users to have
```suggestion
This Kyma version introduces the Istio CNI plugin. The plugin replaces the `istio-init` container, and it provides the same networking functionality, but it doesn't require Istio users to have elevated Kubernetes RBAC permission. 
```

2022-10-18 09:40 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +This Kyma version introduces the Istio CNI plugin. The plugin replaces the Istio `istio-init` container, and it provides the same networking functionality, but it doesn't require Istio users to have
Oh, that totally makes sense! Thanks!

2022-10-18 09:45 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +From this release, Application Gateway in Kyma supports redirects for the HTTP requests in which the URL host remains unchanged.
As discussed, it makes sense, but we usually drop the `on`, so I'd prefer to go with the usual :)

2022-10-18 10:34 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +We've been working as [busy bees](https://www.youtube.com/watch?v=96tOPyuhuJs) to present to you Kyma 2.8. We packed this release with upgrades, updates, and improvements, as well as some changes to
😍

2022-10-18 10:34 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +While we get back to [beeing](https://youtu.be/eBMxaOeREHA?t=8) busy with what's next, you go and explore what we've prepared for you.
rofl

2022-10-18 10:36 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +Check out also our new tutorial on how to [expose workloads in multiple Namespaces with a single APIRule definition](https://kyma-project.io/docs/kyma/2.8/03-tutorials/00-api-exposure/apix-09-expose-
```suggestion
Also, check out our new tutorial on how to [expose workloads in multiple Namespaces with a single APIRule definition](https://kyma-project.io/docs/kyma/2.8/03-tutorials/00-api-exposure/apix-09-expose-workloads-multiple-namespaces/).
```
"also" in that place felt weird to me

2022-10-18 10:54 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The functionality makes the HTTP clients that originally called Application Gateway follow redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body without a
I had to read this sentence several times to parse it correctly in my head. Can we restructure/simplify it? 

```suggestion
Now, the HTTP clients that originally called Application Gateway will seamlessly follow redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body.
```

```suggestion
Now, the HTTP clients that originally called Application Gateway will smoothly follow redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body.
```

Wow it's hard to find an one-word adverb to replace "without issue" 😬  Not completely happy yet but maybe it's a starting point.

2022-10-18 10:54 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +In this release, we also updated the HTTP status codes that Application Gateway returns:
```suggestion
In this release, we also updated the HTTP status codes that Application Gateway returns in the following cases:
```

2022-10-18 10:54 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +- When the Application specified in the path does not exist,
```suggestion
- When the Application specified in the path does not exist.
```

2022-10-18 10:54 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +- When the Application, service or entry is not passed in the path, or
```suggestion
- When the Application, service or entry is not passed in the path.
```

2022-10-18 10:54 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +At the same time, the Serverless engine switched to OTLP as well, and is ready for the awesome future.
I know OneNote says that this is sufficient and thus Serverless doesn't mention it in their own section. But as a reader, scanning just the headlines the current draft creates the impression that nothing happened for Serverless with 2.8.

2022-10-18 11:19 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The functionality makes the HTTP clients that originally called Application Gateway follow redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body without a
It was smooth before as well, but did not include those headers and so on, and that was an issue. Knowing this, would you still rather change the phrasing to what you proposed?

2022-10-18 11:21 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +At the same time, the Serverless engine switched to OTLP as well, and is ready for the awesome future.
I also wondered about it. Do you think we should add a Serverless section, write there that it switched to OTLP and refer to this section?

2022-10-18 11:26 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The functionality makes the HTTP clients that originally called Application Gateway follow redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body without a
Ah I see. So basically, more like that:

```suggestion
Now, the HTTP clients that originally called Application Gateway will follow the whole sequence of redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body.
```

2022-10-18 11:27 UTC, NHingerl commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +At the same time, the Serverless engine switched to OTLP as well, and is ready for the awesome future.
Yep! (if @a-thaler and @kwiatekus agree)

2022-10-18 11:40 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The functionality makes the HTTP clients that originally called Application Gateway follow redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body without a
Mhmm... it's not about the sequence of redirects, but about including stuff that must be included to process it properly at the end. I'll apply one of your suggestions or something based on them to make it clearer and not demanding heavy processing.

2022-10-18 12:21 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +The functionality makes the HTTP clients that originally called Application Gateway follow redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body without a
```suggestion
This functionality lets the HTTP client choose whether to resolve redirects within the scope of the same API. 
If so chosen, the HTTP client that originally called Application Gateway follows redirects through the Gateway, passing authorization, custom headers, URL parameters, and the body.
```

2022-10-18 12:36 UTC, kwiatekus commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +At the same time, the Serverless engine switched to OTLP as well, and is ready for the awesome future.
Additional input to serverless could look like:

Following the changes in Observability and opening new Open Telemetry Protocol compliant endpoints in Jaeger Serverless engine configure  functions to  sendtrace data to that new OTLP endpoint.
Functions build before 2.8 will continue sending trace data to the previous endpoint.
Read more [here](https://kyma-project.io/docs/kyma/main/05-technical-reference/00-configuration-parameters/svls-02-environment-variables/)

2022-10-18 13:47 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +- [Observability](#observability) - component updates, improved secret rotation support for LogPipelines, Kiali deprecation
I did that and then @a-thaler changed it to lowercase.

2022-10-18 13:48 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +This Kyma version introduces the Istio CNI plugin. The plugin replaces the `istio-init` container, and it provides the same networking functionality, but it doesn't require Istio users to have elevat
I'd rather keep the pronoun, as it's sort of a separate piece of information, not something that's been modified in Kyma.

2022-10-18 13:51 UTC, majakurcius commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +- [Observability](#observability) - component updates, improved secret rotation support for LogPipelines, Kiali deprecation
But it's still uppercase anywhere else. I'm unifying that. Thanks!

2022-10-18 13:51 UTC, grego952 commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +- [Observability](#observability) - component updates, improved secret rotation support for LogPipelines, Kiali deprecation
Ok, so I think it should be changed to lowercase in your Intro and the Logging section as well

2022-10-19 06:27 UTC, strekm submitted a review, later dismissed
/meow

2022-10-19 07:13 UTC, kwiatekus approved these changes

2022-10-19 08:02 UTC, grego952 submitted a review, later dismissed

2022-10-19 08:19 UTC, a-thaler submitted a review, later dismissed

2022-10-19 08:19 UTC, IwonaLanger submitted a review, later dismissed

2022-10-19 11:29 UTC, k15r requested changes

2022-10-19 11:29 UTC, k15r commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +### NATS upgraded to 2.9.0
```suggestion
### NATS upgraded to 2.9.3
```

2022-10-19 11:29 UTC, k15r commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +In Kyma 2.8, we upgraded the Eventing stack to NATS 2.9.0.
```suggestion
In Kyma 2.8, we upgraded the Eventing stack to NATS 2.9.3.
```

2022-10-19 11:29 UTC, k15r commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +For more details on this version, see the official [NATS 2.9.0 release notes](https://docs.nats.io/release-notes/whats_new#server-release-v2.9.0).
For the reviewer: Even though we upgrade to 2.9.3 we can only link to 2.9.0 here. release notes for 2.9.3 simply dont exist

2022-10-19 11:48 UTC, k15r requested changes

2022-10-19 11:48 UTC, k15r commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +- [Eventing](#eventing) - upgrade to NATS 2.9.0
this will be already part of 2.7.3
```suggestion
```

2022-10-19 11:48 UTC, k15r commented on content/blog-posts/2022-10-20-release-notes-2.8/index.md
> +
Already part of 2.7.3
```suggestion
```

2022-10-19 12:37 UTC, k15r submitted a review, later dismissed

2022-10-19 14:43 UTC, IwonaLanger approved these changes

2022-10-21 14:16 UTC, merged