add release notes 2.9
kyma-project/website pull request #915
Opened 2022-11-15 13:47 UTC by grego952

**Description**

Changes proposed in this pull request:

- Add release notes for Kyma 2.9

**Related issue(s)**
Resolves #914

2022-11-15 15:43 UTC, k15r approved these changes

2022-11-15 16:29 UTC, kwiatekus commented
Roses are red, violets are blue, and my approval is green :)
/lgtm

2022-11-15 16:29 UTC, kwiatekus approved these changes

2022-11-16 09:35 UTC, akgalwas approved these changes

2022-11-16 09:40 UTC, grego952 commented on content/blog-posts/2022-11-17-release-notes-2.9/index.md
> +- [CLI](#cli) - Function commands adjusted to the new API version
Actually, I think we're talking about Kyma Functions so it should be capitalized.

2022-11-16 09:41 UTC, IwonaLanger approved these changes

2022-11-16 09:43 UTC, strekm approved these changes

2022-11-16 14:33 UTC, a-thaler commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +Roses are red, violets are blue, and Kyma is ready with the new updates for you. This release comes with a lot of changes. For example, we migrated the Fluent Bit component from Logging to Telemetry,
The migration of fluenbit happened some time ago, now it is just the final removal. I think that should not be mentioned as a highlight. Maybe use the k8s 1.24 support instead. Also I would avoid to take about a lot of changes as the list is quite small..
Providing a preview on tracing maybe is also not a highlight of a release

2022-11-16 14:33 UTC, a-thaler commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +- [Observability](#observability) - Loki deprecation, Fluent Bit migration, component updates
```suggestion
- [Observability](#observability) - Loki deprecation, component updates
```

2022-11-16 14:36 UTC, a-thaler requested changes
We need to await the outcome of https://github.com/kyma-project/kyma/issues/16105 as it gets mentioned in the general section

2022-11-16 14:54 UTC, friedrichwilken commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +
```suggestion
## Eventing

### NATS server

NATS server was updated to version 2.9.6. For more information read the [NATS server v2.9.6 release notes](https://github.com/nats-io/nats-server/releases/tag/v2.9.6).
```

2022-11-16 14:54 UTC, friedrichwilken commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +
```suggestion
- [Eventing](#eventing) - NATS server updated to `v2.9.6`
```

2022-11-17 07:14 UTC, Sawthis requested changes

2022-11-17 07:14 UTC, Sawthis commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +While working on that, we've already taken major steps towards the next Kubernetes version 1.25 by cleaning all PodSecurityPolicies (PSP) and revising all SecurityContexts. Remember that you may need
@a-thaler do we need to change this sentence due to https://github.com/kyma-project/kyma/issues/16105 ? In the link which is provided there is "5. Disable PodSecurityPolicy" paragraph where is recommended to turn off admission controller.

2022-11-17 12:57 UTC, a-thaler commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +Node.js 12 has reached the end of its life. Therefore, followed by the depreciation of Node.js 12 Serverless runtime, we decided to finally remove it from the list of the available Function runtimes.
Do you have a link to migration notes published with previous release notes? What as a user I need to do now?

2022-11-17 13:09 UTC, a-thaler commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +While working on that, we've already taken major steps towards the next Kubernetes version 1.25 by cleaning all PodSecurityPolicies (PSP) and revising all SecurityContexts. Remember that you may need
Maybe we write that you should prepare by reading the document?..
Anyway we need an addition. As we removed the generic kyma PSP, your pods might be prevented from being deployed now as the providers default policies are not fitting. So on an upgrade to this kyma version you might need to introduce proper PSPs to compensate the removal (see here: https://github.com/kyma-project/kyma/pull/15929) or you disable the PSP admission controller already and switch to the new security admission model

2022-11-17 13:48 UTC, Sawthis submitted a review, later dismissed

2022-11-17 13:53 UTC, kwiatekus commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +Node.js 12 has reached the end of its life. Therefore, followed by the depreciation of Node.js 12 Serverless runtime, we decided to finally remove it from the list of the available Function runtimes.
@grego952 here is a link to depreciation notice ( part of 2.1 RN )
https://kyma-project.io/blog/2022/3/25/release-notes-21/#node-js-12-deprecated

As per what users need to do:

Your Node.js 12 functions' workloads will continue to run but you will not be able to edit them without changing the runtime field as well. Sooner or later you should change the spec of your existing Node.js 12 based functions and change the `runtime`  field  to either `nodejs14` or `nodejs16`

2022-11-17 15:56 UTC, friedrichwilken submitted a review, later dismissed

2022-11-17 15:56 UTC, friedrichwilken commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +## Eventing
```suggestion

## Eventing
```

2022-11-17 15:56 UTC, friedrichwilken commented on content/blog-posts/2022-11-18-release-notes-2.9/index.md
> +NATS server was updated to version 2.9.6. For more information read the [NATS server v2.9.6 release notes](https://github.com/nats-io/nats-server/releases/tag/v2.9.6).
```suggestion
NATS server was updated to version 2.9.6. For more information read the [NATS server v2.9.6 release notes](https://github.com/nats-io/nats-server/releases/tag/v2.9.6).

The stream setup has been modified for the case of full message storages. This state will now lead to the rejection of new messages and the return of error code 507. These changes where done to prevent the deletion of old messages. 
```

2022-11-18 08:18 UTC, IwonaLanger submitted a review, later dismissed

2022-11-18 11:51 UTC, a-thaler approved these changes

2022-11-21 10:32 UTC, IwonaLanger submitted a review, later dismissed

2022-11-22 07:16 UTC, IwonaLanger approved these changes

2022-11-22 07:24 UTC, Sawthis approved these changes

2022-11-22 07:32 UTC, merged

2022-11-22 08:26 UTC, friedrichwilken reviewed
/lgtm