Initial blog post
kyma-project/website pull request #917
Opened 2022-11-18 14:37 UTC by videlov

**Description**

Changes proposed in this pull request:

- Blog post for Istio XFF support

**Related issue(s)**

https://github.com/kyma-project/kyma/issues/15865
https://github.com/kyma-project/kyma/issues/16041

2022-11-18 14:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/website?pullRequest=917) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/website?pullRequest=917) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/website?pullRequest=917) it.</sub>

2022-11-22 07:12 UTC, strekm requested changes
what i miss here is explanation how to configure `numTruestedProxies`, what that number means. In point 3 i would advice to secure workload with jwt. Finally what is missing is granting access to workload for specific IP

2022-11-29 11:29 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +In order to provide a simplified and reliable way for applying changes to Istio Service Mesh, we introduced the Kyma Istio Custom Resource (CR). This improvement adds another layer of configuration a
```suggestion
In order to provide a simplified and reliable way of applying changes to the Istio Service Mesh, we introduced the Kyma Istio Custom Resource (CR). This improvement adds another layer of configuration abstraction for the user and will enable us to utilize the Kubernetes controller pattern in the future.
```

2022-11-29 11:57 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +Until now, managed Kyma Istio installation did not allow configuring Istio Service Mesh in such a way, that client attributes could be forwarded to the destination workloads. For managed Kyma install
```suggestion
Until now, the managed Kyma Istio installation did not allow configuring Istio Service Mesh in such a way that client attributes could be forwarded to destination workloads. For the managed Kyma installation, changes applied to the Istio Service Mesh configuration directly by the user were reset to default settings by Kyma Reconciler.
```

2022-12-01 12:06 UTC, IwonaLanger commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +I'm part of the Kyma team working on Istio and API Gateway features. In this blog post, we would like to introduce the highly requested configuration support in Kyma Istio for forwarding an external
```suggestion
I'm part of the Kyma team working on Istio and API Gateway features. In this blog post, we would like to introduce the highly requested configuration support in Kyma Istio for forwarding an external client IP address to destination workloads. Read on to learn more about this improvement and see how to configure it.
```

2022-12-01 12:06 UTC, IwonaLanger commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +Many applications need to know the client IP address of an originating request to behave properly. Usual use-cases include workloads that require the client IP address to restrict their access. The a
```suggestion
Many applications need to know the client IP address of an originating request to behave properly. Usual use-cases include workloads that require the client IP address to restrict their access. The ability to provide client attributes to services has long been a staple of reverse proxies. To forward client attributes to destination workloads, proxies use the `X-Forwarded-For` (XFF) header. For more information on XFF, see the [IETF’s RFC documentation](https://tools.ietf.org/html/rfc7239) and [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for).
```

2022-12-01 12:06 UTC, IwonaLanger commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +You may take a look at the [Kyma Istio CR reference documentation](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/oper-01-istio/) for further details.
The link doesn't work.

2022-12-01 12:06 UTC, IwonaLanger commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +## Final words
```suggestion
## Final remarks
```

2022-12-02 13:03 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +You may take a look at the [Kyma Istio CR reference documentation](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/oper-01-istio/) for further details.
I edited my suggestion and updated the link. It works now.

2022-12-02 13:06 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +You may take a look at the [Kyma Istio CR reference documentation](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/oper-01-istio/) for further details.
I edited my suggestion and updated the link. It works now.

2022-12-07 12:24 UTC, videlov commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +
Please check if this would be enough.

2022-12-08 08:38 UTC, videlov commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +kubectl patch istios/istio-operator -n kyma-system --type merge -p '{"spec":{"config":{"numTrustedProxies": 2}}}'
Good catch, thank you.

2022-12-09 09:14 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +2. Allow Kyma Istio Reconciler to apply the changes to Istio ConfigMap. To trigger it without waiting, run:
```suggestion
2. Allow Kyma Istio Reconciler to apply the changes to Istio ConfigMap. To trigger it right away, run:
```

2022-12-09 10:20 UTC, videlov commented
We merge it after Kyma 2.10 is released.

2022-12-09 10:41 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +5. You can also apply the `AuthorizationPolicy` for the Istio gateway to secure workload access by the IP address. To do so, run:
```suggestion
5. You can also apply the `AuthorizationPolicy` to the Istio gateway in order to secure workload access by the IP address. To do so, run:
```

2022-12-13 07:47 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +I'm part of the Kyma team working on Istio and API Gateway features. In this blog post, I would like to introduce you to the highly requested configuration support in Kyma Istio for forwarding an ext
```suggestion
I'm part of the Kyma team working on Istio and API Gateway features. In this blog post, I would like to introduce the highly requested configuration support in Kyma Istio for forwarding an external client IP address to destination workloads. Read on to learn more about this improvement and see how to configure it.
```

2022-12-14 13:00 UTC, IwonaLanger submitted a review, later dismissed

2023-01-10 13:14 UTC, nataliasitko commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +
```suggestion
Follow this example to learn how to forward an external client IP address to the destination workload using the newly introduced configuration support in Kyma Istio. To be able to replicate the steps, you need to have Kyma 2.10 installed. If you're reading the blog post before Kyma 2.10 is available, please come back after the release.
```

2023-01-10 14:45 UTC, IwonaLanger commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +I'm part of the Kyma team working on Istio and API Gateway features. In this blog post, I would like to introduce the highly requested configuration support in Kyma Istio for forwarding an external c
```suggestion
I'm part of the Kyma team working on Istio and API Gateway features. In this blog post, I would like to introduce the highly requested configuration support in Kyma Istio for forwarding an external client IP address to destination workloads. 

> **NOTE** The support comes with version 2.10 of Kyma. 

Read on to learn more about this improvement and see how to configure it.
```

2023-01-10 14:45 UTC, IwonaLanger commented on content/blog-posts/2022-11-18-istio-xff-support/index.md
> +Follow this example to learn how to forward an external client IP address to the destination workload using the newly introduced configuration support in Kyma Istio. To be able to replicate the steps
```suggestion
Follow this example to learn how to forward an external client IP address to the destination workload using the newly introduced configuration support in Kyma Istio. 

> **NOTE** To be able to replicate the steps, you need to have Kyma 2.10 installed. If you're reading the blog post before Kyma 2.10 is available, please come back after the release.


```

2023-01-10 14:52 UTC, nataliasitko approved these changes

2023-01-11 07:58 UTC, strekm approved these changes
/meow

2023-01-11 08:29 UTC, videlov commented
/retest

2023-01-11 08:37 UTC, IwonaLanger approved these changes

2023-01-11 08:39 UTC, merged