Release Notes for Kyma 2.10
kyma-project/website pull request #939
Opened 2023-01-11 10:09 UTC by IwonaLanger

**Description**

Changes proposed in this pull request:

Release notes for Kyma 2.10

**Related issue(s)**

2023-01-11 11:53 UTC, nataliasitko commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +With this version of Kyma, we introduce [Istio CR](https://kyma-project.io/docs/kyma/main/05-technical-reference/00-custom-resources/oper-01-istio/) supporting the configuration of `numTrustedProxies
```suggestion
With this version of Kyma, we introduce [Istio CR](https://kyma-project.io/docs/kyma/main/05-technical-reference/00-custom-resources/oper-01-istio/) supporting the configuration of `numTrustedProxies`. Read about the [Support for XFF with Istio](https://github.com/kyma-project/website/blob/main/content/blog-posts/2023-01-11-istio-xff-support/index.md) to learn how to configure Istio CR and secure your workload on a forwarded client IP.
```

2023-01-11 11:53 UTC, nataliasitko commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +From now Application Gateway will use the `kyma-system` Namespace instead of the `kyma-integration` Namespace. The secrets related to the Namespace are not removed automatically in the process of upg
```suggestion
From now Application Gateway will use the `kyma-system` Namespace instead of the `kyma-integration` Namespace. The Secrets related to the Namespace are not removed automatically in the process of upgrading Kyma to version 2.10. To remove them, you must run the [migration script]( https://github.com/kyma-project/kyma/blob/main/docs/assets/2.9-2.10-OS-copy-secrets-to-system-namespace.sh) after successfully migrating from Kyma 2.9 to Kyma 2.10. 
```

2023-01-11 11:53 UTC, nataliasitko commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +NATS server update to version 2.9.9 improves overall stability and performance, and prevents security issues. For more details, see the NATS server [Release v2.9.9]( https://github.com/nats-io/nats-s
```suggestion
The NATS server update to version 2.9.9 improves overall stability and performance, and prevents security issues. For more details, see the NATS server [Release v2.9.9]( https://github.com/nats-io/nats-server/releases/tag/v2.9.9).
```

2023-01-11 12:02 UTC, grego952 commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +With this version of Kyma, we introduce [Istio CR](https://kyma-project.io/docs/kyma/main/05-technical-reference/00-custom-resources/oper-01-istio/) supporting the configuration of `numTrustedProxies
```suggestion
With this version of Kyma, we introduced [Istio custom resource (CR)](https://kyma-project.io/docs/kyma/main/05-technical-reference/00-custom-resources/oper-01-istio/) supporting the configuration of `numTrustedProxies`. Read about the [Support for XFF with Istio](https://github.com/kyma-project/website/blob/main/content/blog-posts/2023-01-11-istio-xff-support/index.md) to learn how to configure Istio CR and secure your workload on a forwarded client IP.
```

2023-01-11 13:30 UTC, franpog859 approved these changes

2023-01-11 13:38 UTC, friedrichwilken requested changes

2023-01-11 13:38 UTC, friedrichwilken commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +The NATS server update to version 2.9.9 improves overall stability and performance, and prevents security issues. For more details, see the NATS server [Release v2.9.9]( https://github.com/nats-io/na
Because of release blocking issues, we will have to change the release notes:

```suggestion
### NATS
Introduced a `System Account` user to allow full leverage of the NATS-cli ([Further reads](https://kyma-project.io/docs/kyma/2.10/04-operation-guides/operations/evnt-03-nats-server-system-events). 

### Metrics 
We exposed new metrics for backend latency.
Also, we have introduced consistent naming for all metrics exposed by EPP. 
Further reads: [Kyma docs](https://kyma-project.io/docs/kyma/2.10/04-operation-guides/operations/evnt-02-eventing-metrics) .
```

2023-01-11 14:27 UTC, IwonaLanger commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +The NATS server update to version 2.9.9 improves overall stability and performance, and prevents security issues. For more details, see the NATS server [Release v2.9.9]( https://github.com/nats-io/na
> Because of release blocking issues, we will have to change the release notes:

Right, I'll edit the RNs.

2023-01-11 15:16 UTC, friedrichwilken submitted a review, later dismissed
/lgtm

2023-01-12 08:00 UTC, a-thaler commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +- [Observability](#observability) – Kiali and monitoring deprecation
```suggestion
- [Observability](#observability) – Monitoring deprecation
```
Kiali is just a reminder

2023-01-12 09:30 UTC, strekm submitted a review, later dismissed
/meow

2023-01-12 09:34 UTC, a-thaler commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +The first version of the [revamped tracing](https://kyma-project.io/docs/kyma/main/01-overview/main-areas/telemetry/telemetry-03-traces/) feature is out. Under the umbrella of the telemetry module, a
```suggestion
The first version of the new [configurable tracing](https://kyma-project.io/docs/kyma/main/01-overview/main-areas/telemetry/telemetry-03-traces/) feature is available. Under the umbrella of the telemetry module, a new CRD TracePipeline is available. That new API will manage an OpenTelemetry Collector which supports you integrating the trace aspects within a runtime into OTLP-based backends. For now, Basic Authentication is supported, and further ways of authentication will be added soon.
```

2023-01-12 09:35 UTC, a-thaler commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +Kiali was deprecated with Kyma 2.8 and will be removed in Kyma 2.11. For more details, see the blog post on [Kiali deprecation](https://kyma-project.io/blog/2022/10/10/Kiali-deprecation).
Maybe put something like "Reminder" in front?

2023-01-12 10:02 UTC, dbadura submitted a review, later dismissed

2023-01-12 11:01 UTC, IwonaLanger commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +Kiali was deprecated with Kyma 2.8 and will be removed in Kyma 2.11. For more details, see the blog post on [Kiali deprecation](https://kyma-project.io/blog/2022/10/10/Kiali-deprecation).
@a-thaler We don't use this kind of panel in our documentation. Just NOTE, TIP or CAUTION. I suggest expressing the idea that the info was published before with the phrase: As announced in the blog post...
However, if you insist on using "Reminder", I'll change the note.

2023-01-12 11:45 UTC, a-thaler commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +Kiali was deprecated with Kyma 2.8 and will be removed in Kyma 2.11. For more details, see the blog post on [Kiali deprecation](https://kyma-project.io/blog/2022/10/10/Kiali-deprecation).
I don't insist on it. I thought we should make it more explicit that it got already deprecated and this is just another warning that the removal will come. If you think it is good enough, I'm fine :)

2023-01-12 11:45 UTC, a-thaler submitted a review, later dismissed

2023-01-12 11:56 UTC, grego952 commented
/retest

2023-01-12 13:47 UTC, a-thaler submitted a review, later dismissed

2023-01-13 10:44 UTC, rakesh-garimella commented on content/blog-posts/2023-01-12-release-notes-2.10/index.md
> +Kyma 2.10 brings the update to the latest Prometheus images (version 2.40.7), which resolves the security vulnerabilities.
do we want to specify image updated to resolve security vulnerabilites ? Cant we just say images have been updated ?

2023-01-17 07:40 UTC, grego952 approved these changes

2023-01-17 07:46 UTC, merged